name: zenius
summary: A Cli for Setup Projects for React web and mobile native 
description: |
  A Cli for Setup Projects for React web and mobile native 
version: '1.0'
base: core20

apps:
  Build:
    command: go build

parts:
  zenius:
    plugin: go
    source: .
    source-type: git
    # go-importpath: github.com/ANDRUXUIS/ProjectsSetup_CLI