name: Build cli and Deploy to npm

on:
  push:
    branches: [ master ]


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Build Go Programme
      run: go build -v

    - name: Publish to npm
      steps:
        - uses: actions/checkout@v1
        - uses: actions/setup-node@v1
          with:
            node-version: 10
        - run: npm ci
        - uses: JS-DevTools/npm-publish@v1
          with:
            token: ${{ secrets.NPM_TOKEN }}